---
- name: Install OpenSlides dependencies
  become: yes
  become_method: su
  pacman:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
  - sudo
  - redis
  - python2-psycopg2  # Needed for ansible
  - python-psycopg2  # Needed for OpenSlides
  - python-pip

- name: Install postgresql
  pacman:
    name: postgresql
    state: present
  register: postgresql_install

- name: Install nginx
  when: openslides_nginx_domains or openslides_nginx_global
  become: yes
  pacman:
    name: nginx
    state: present

- name: Install git and development tools
  when: openslides_use_git
  become: yes
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
  - git
  - npm

- name: Set locale
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: Initial postgres database
  command: initdb --locale en_US.UTF-8 -E UTF8 -D /var/lib/postgres/data
  args:
    creates: /var/lib/postgres/data/PG_VERSION
  become: yes
  become_user: postgres

- set_fact:
    pip_executable: pip
    openslides_distro_fround: true
    openslides_bin: /usr/bin/openslides
    daphne_bin: /usr/bin/daphne
    redis_service: redis
    postgres_connection: local
